server:
   port:8080
spring:
  thymeleaf:
    cache: true  #
  datasource:
    username: root
    password: 1598
    url: jdbc:mysql://localhost:3306/who_read?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

